networks:
  hospital-network:
    driver: bridge
    ipam:
      config:
        - subnet: 111.222.32.0/24

services:
  mongodb:
    image: mongo:latest
    container_name: main-mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - "mongo-volume:/data/db"
      - "mongo-config:/data/configdb"
      - ./key.txt:/etc/mongodb/pki/keyfile.txt
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: YOUR_PASSWORD
    networks:
      hospital-network:
        ipv4_address: 111.222.32.2
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--keyFile", "/etc/mongodb/pki/keyfile.txt"]
  
  mongodb2:
    image: mongo:latest
    container_name: sec-mongodb
    restart: always
    ports:
      - '27018:27018'
    volumes:
      - "mongo2-volume:/data/db"
      - "mongo2-config:/data/configdb"
      - ./key.txt:/etc/mongodb/pki/keyfile.txt
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: YOUR_PASSWORD
    networks:
      hospital-network:
        ipv4_address: 111.222.32.3
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27018", "--keyFile", "/etc/mongodb/pki/keyfile.txt"]
    depends_on:
      - mongodb
  
  backend:
    build: .
    container_name: node-api
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env 
    depends_on:
      - mongodb2
    networks:
      - hospital-network

  caddy:
    image: caddy:latest
    container_name: caddy-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
    networks:
      - hospital-network

volumes:
  mongo-volume:
  mongo2-volume:
  mongo-config:
  mongo2-config:
  caddy_data:
  caddy_config: